"use client"

import type { ExportDataset } from "./types"

/**
 * Generate a Tally Prime / Tally.ERP 9 import XML containing both Sales and
 * Purchase vouchers for the period. The CA imports this via Tally → Import → XML.
 *
 * NOTE: Real-world Tally imports require the customer's exact Ledger names to
 * match. We emit standard ledgers ("Sales A/c", "Purchase A/c", "CGST", "SGST",
 * "IGST", and a generic "Cash" / "Sundry Debtors" party). The CA can map them
 * to their own COA on import.
 */
export function buildTallyXml(data: ExportDataset): string {
    const valid = data.sales.filter((s) => s.bill_status !== "VOID")
    const company = escape(data.tenant.name)

    const salesVouchers = valid.map((s) => salesVoucher(s, company)).join("\n")
    const purchaseVouchers = data.purchases.map((p) => purchaseVoucher(p, company)).join("\n")

    return `<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
    <HEADER>
        <TALLYREQUEST>Import Data</TALLYREQUEST>
    </HEADER>
    <BODY>
        <IMPORTDATA>
            <REQUESTDESC>
                <REPORTNAME>Vouchers</REPORTNAME>
                <STATICVARIABLES>
                    <SVCURRENTCOMPANY>${company}</SVCURRENTCOMPANY>
                </STATICVARIABLES>
            </REQUESTDESC>
            <REQUESTDATA>
${salesVouchers}
${purchaseVouchers}
            </REQUESTDATA>
        </IMPORTDATA>
    </BODY>
</ENVELOPE>`
}

function salesVoucher(s: ExportDataset["sales"][number], company: string): string {
    const date = tallyDate(s.invoice_date)
    const partyName = s.customer_name ? escape(s.customer_name) : "Sundry Debtors"
    const total = num(s.grand_total)
    const taxable = num(s.taxable_amount)

    const taxAllocations: string[] = []
    if (s.cgst_amount > 0) taxAllocations.push(taxAllocation("CGST", num(s.cgst_amount)))
    if (s.sgst_amount > 0) taxAllocations.push(taxAllocation("SGST", num(s.sgst_amount)))
    if (s.igst_amount > 0) taxAllocations.push(taxAllocation("IGST", num(s.igst_amount)))

    return `                <VOUCHER REMOTEID="${s.invoice_number}" VCHTYPE="Sales" ACTION="Create" OBJVIEW="Invoice Voucher View">
                    <DATE>${date}</DATE>
                    <NARRATION>Generated by RestoPOS — ${escape(s.invoice_number)}</NARRATION>
                    <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
                    <VOUCHERNUMBER>${escape(s.invoice_number)}</VOUCHERNUMBER>
                    <PARTYLEDGERNAME>${partyName}</PARTYLEDGERNAME>
                    <BASICBASEPARTYNAME>${partyName}</BASICBASEPARTYNAME>
                    ${s.customer_gstin ? `<PARTYGSTIN>${escape(s.customer_gstin)}</PARTYGSTIN>` : ""}
                    <ALLLEDGERENTRIES.LIST>
                        <LEDGERNAME>${partyName}</LEDGERNAME>
                        <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
                        <AMOUNT>-${total}</AMOUNT>
                    </ALLLEDGERENTRIES.LIST>
                    <ALLLEDGERENTRIES.LIST>
                        <LEDGERNAME>Sales A/c</LEDGERNAME>
                        <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
                        <AMOUNT>${taxable}</AMOUNT>
                    </ALLLEDGERENTRIES.LIST>
                    ${taxAllocations.join("\n                    ")}
                </VOUCHER>`
}

function purchaseVoucher(p: ExportDataset["purchases"][number], company: string): string {
    const date = tallyDate(p.invoice_date)
    const vendor = escape(p.vendor_name)
    const total = num(p.grand_total)
    const taxable = num(p.taxable_amount)

    const taxAllocations: string[] = []
    if (p.cgst_amount > 0) taxAllocations.push(taxAllocation("CGST (ITC)", num(p.cgst_amount)))
    if (p.sgst_amount > 0) taxAllocations.push(taxAllocation("SGST (ITC)", num(p.sgst_amount)))
    if (p.igst_amount > 0) taxAllocations.push(taxAllocation("IGST (ITC)", num(p.igst_amount)))

    return `                <VOUCHER REMOTEID="${p.purchase_number}" VCHTYPE="Purchase" ACTION="Create" OBJVIEW="Invoice Voucher View">
                    <DATE>${date}</DATE>
                    <NARRATION>Vendor invoice ${escape(p.vendor_invoice_no ?? p.purchase_number)}</NARRATION>
                    <VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>
                    <VOUCHERNUMBER>${escape(p.purchase_number)}</VOUCHERNUMBER>
                    <PARTYLEDGERNAME>${vendor}</PARTYLEDGERNAME>
                    <BASICBASEPARTYNAME>${vendor}</BASICBASEPARTYNAME>
                    ${p.vendor_gstin ? `<PARTYGSTIN>${escape(p.vendor_gstin)}</PARTYGSTIN>` : ""}
                    <ALLLEDGERENTRIES.LIST>
                        <LEDGERNAME>${vendor}</LEDGERNAME>
                        <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
                        <AMOUNT>${total}</AMOUNT>
                    </ALLLEDGERENTRIES.LIST>
                    <ALLLEDGERENTRIES.LIST>
                        <LEDGERNAME>Purchase A/c</LEDGERNAME>
                        <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
                        <AMOUNT>-${taxable}</AMOUNT>
                    </ALLLEDGERENTRIES.LIST>
                    ${taxAllocations.map((s) => s.replace("<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>", "<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>").replace(/<AMOUNT>([0-9.]+)<\/AMOUNT>/, "<AMOUNT>-$1</AMOUNT>")).join("\n                    ")}
                </VOUCHER>`
}

function taxAllocation(ledger: string, amount: string) {
    return `<ALLLEDGERENTRIES.LIST>
                        <LEDGERNAME>${ledger}</LEDGERNAME>
                        <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
                        <AMOUNT>${amount}</AMOUNT>
                    </ALLLEDGERENTRIES.LIST>`
}

function tallyDate(iso: string): string {
    const d = new Date(iso)
    return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}`
}

function num(n: number): string {
    return n.toFixed(2)
}

function escape(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}
